name: testbinder
channels:
    - conda-forge
dependencies:
    - python=3.10
    - pip
    - gdal
    - numpy
    - scipy
    - pandas
    - bokeh
    - matplotlib
    - pip:
        - git+https://github.com/hectornieto/pypro4sail
        - git+https://github.com/hectornieto/pyTSEB
        - git+https://github.com/hectornieto/model_evaluation
        - git+https://github.com/radosuav/pyDMS
